version: '2'

volumes:
  backup-data:

services:
  backup:
    image: pg_dumper-s3
    build: .
    entrypoint: sh
    tty: true
    #entrypoint: sh -c "sleep 30 && /entrypoint"
    volumes:
    - backup-data:/backups
    environment:
      - S3_ENDPOINT_URL=http://s3:9000
      - S3_ACCESS_KEY_ID=minio
      - S3_SECRET_ACCESS_KEY=minio123
      - S3_BUCKET=backups
      - DB_HOST=db
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=test
      - BACKUP_DIR=/backups

  db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=test
    - POSTGRES_DB=test
    - POSTGRES_PASSWORD=test

  s3:
    image: minio/minio:RELEASE.2019-05-23T00-29-34Z
    entrypoint: sh
    command: -c 'mkdir -p /data/backups && /usr/bin/minio server /data'
    tmpfs:
     - /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
