version: '2'

services:
  backup:
    image: gcavalcante8808/pgdump-s3
    environment:
     - DB_HOST
     - DB_USER
     - DB_PASSWORD
     - DB_NAME
     - BACKUP_DIR
     - S3_ENDPOINT_URL
     - S3_ACCESS_KEY_ID
     - S3_SECRET_ACCESS_KEY
     - S3_BUCKET

